apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dev-project
  namespace: argocd
spec:
  description: Proyecto para ambiente de desarrollo
  
  sourceRepos:
    - 'https://github.com/tu-usuario/gitops-lab.git'
    - 'https://charts.helm.sh/stable'
    - 'https://argoproj.github.io/argo-helm'
  
  destinations:
    - namespace: 'dev-*'
      server: https://kubernetes.default.svc
    - namespace: 'dev'
      server: https://kubernetes.default.svc
  
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
    - group: 'apps'
      kind: Deployment
    - group: 'apps'
      kind: ReplicaSet
    - group: 'apps'
      kind: StatefulSet
    - group: 'apps'
      kind: DaemonSet
    - group: ''
      kind: Service
    - group: ''
      kind: ConfigMap
    - group: ''
      kind: Secret
    - group: 'networking.k8s.io'
      kind: Ingress
  
  namespaceResourceWhitelist:
    - group: ''
      kind: '*'
    - group: 'apps'
      kind: '*'
    - group: 'networking.k8s.io'
      kind: '*'
    - group: 'batch'
      kind: '*'
  
  roles:
    - name: dev-admin
      description: Administrador del ambiente de desarrollo
      policies:
        - p, proj:dev-project:dev-admin, applications, *, dev-project/*, allow
        - p, proj:dev-project:dev-admin, repositories, *, *, allow
        - p, proj:dev-project:dev-admin, certificates, *, *, allow
        - p, proj:dev-project:dev-admin, clusters, *, *, allow
      groups:
        - dev-team
  
    - name: dev-developer
      description: Desarrollador del ambiente de desarrollo
      policies:
        - p, proj:dev-project:dev-developer, applications, get, dev-project/*, allow
        - p, proj:dev-project:dev-developer, applications, sync, dev-project/*, allow
        - p, proj:dev-project:dev-developer, applications, action/*, dev-project/*, allow
      groups:
        - dev-developers
