# Configuración para ambiente de desarrollo
replicaCount: 1

image:
  tag: "1.21"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: nginx-dev.local
      paths:
        - path: /
          pathType: Prefix

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

config:
  customHtml: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>GitOps Lab - DEV Environment</title>
        <style>
            body { font-family: Arial, sans-serif; margin: 40px; background: #e8f5e8; }
            .container { max-width: 800px; margin: 0 auto; }
            .header { background: #27ae60; color: white; padding: 20px; border-radius: 5px; }
            .content { padding: 20px; background: white; border-radius: 5px; margin-top: 20px; }
        </style>
    </head>
    <body>
        <div class="container">
            <div class="header">
                <h1>🚀 GitOps Lab - DEV</h1>
                <p>Ambiente de Desarrollo</p>
            </div>
            <div class="content">
                <h2>Información del Pod</h2>
                <p><strong>Hostname:</strong> <span id="hostname"></span></p>
                <p><strong>Environment:</strong> Development</p>
                <p><strong>Timestamp:</strong> <span id="timestamp"></span></p>
                <script>
                    document.getElementById('hostname').textContent = window.location.hostname;
                    document.getElementById('timestamp').textContent = new Date().toLocaleString();
                </script>
            </div>
        </div>
    </body>
    </html>
