apiVersion: v2
name: nginx-app
description: Aplicación web Nginx para GitOps Lab
type: application
version: 0.1.0
appVersion: "1.21"
keywords:
  - nginx
  - web
  - gitops
home: https://nginx.org/
sources:
  - https://github.com/nginx/nginx
maintainers:
  - name: GitOps Lab Team
    email: team@gitops-lab.com
