apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>GitOps Lab - Simple App</title>
    </head>
    <body>
        <h1>🚀 GitOps Lab</h1>
        <p>Aplicación simple desplegada con GitOps</p>
        <p>Hostname: <span id="hostname"></span></p>
        <script>
            document.getElementById('hostname').textContent = window.location.hostname;
        </script>
    </body>
    </html>
