apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-basic
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/VictorGSandoval/gitops.git
    targetRevision: HEAD
    path: manifests/basic
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true