replicaCount: 1

image:
  tag: "1.21"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  hosts:
    - host: helm-app-dev.local
      paths:
        - path: /
          pathType: Prefix

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi
